# Site settings
title: henyuer's blog
description: >
  This is a simple website built with Jekyll and hosted on GitHub Pages.
baseurl: "" # 站点的基础 URL，通常留空
url: "https://yourusername.github.io" # 你的 GitHub Pages 网站地址

# Build settings
markdown: kramdown
theme: minima

# Optional settings
plugins:
  - jekyll-feed # 自动生成 RSS feed
