# theme: jekyll-theme-minimal
# remote_theme: pages-themes/minimal@v0.2.0
title: henyuer's homepage
# description: 个人博客主页
show_downloads: true
# google_analytics:
logo: /assets/images/avatar.png
plugins:
  - jekyll-seo-tag
# - jekyll-remote-theme