# theme: jekyll-theme-minimal
# remote_theme: pages-themes/minimal@v0.2.0
title: henyuer's homepage
# description: 个人博客主页
show_downloads: true
# google_analytics:
logo: /assets/images/avatar.png

pwa:
  enabled: true # The option for PWA feature (installable)
  cache:
    enabled: true # The option for PWA offline cache
    # Paths defined here will be excluded from the PWA cache.
    # Usually its value is the `baseurl` of another website that
    # shares the same domain name as the current website.
    deny_paths:
      # - "/example"  # URLs match `<SITE_URL>/example/*` will not be cached by the PWA

# the avatar on sidebar, support local or CORS resources
avatar: "/commons/avatar.jpg"

plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
# - jekyll-remote-theme