source "https://rubygems.org"

gem "jekyll","~>4.4" 
gem "jekyll-remote-theme"
gem "jekyll-seo-tag"
gem "jekyll-include-cache"
gem "jekyll-archives"
gem "jekyll-paginate"
gem "jekyll-theme-chirpy"
# gem "jekyll-sass-converter"